---
on:
  push:
  workflow_dispatch:

jobs:
  ver:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Test env variables
        run: |
          docker --version

  build:
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
        env:
          - name: dev
            aws_key_id: AWS_GITHUB_ACCESS_KEY_ID
            aws_secret: AWS_GITHUB_SECRET_ACCESS_KEY
          - name: contractors
            aws_key_id: CONTRACTORS_AWS_ACCESS_KEY_ID
            aws_secret: CONTRACTORS_AWS_SECRET_ACCESS_KEY
          - name: training
            aws_key_id: TRAINING_AWS_ACCESS_KEY_ID
            aws_secret: TRAINING_AWS_SECRET_ACCESS_KEY
    steps:
      - uses: actions/checkout@v2
      - name: Test env variables
        env:
          ENV: ${{ matrix.env.name }}
          AWS_KEY_NAME: ${{ secrets[matrix.env.aws_key_id] }}
          AWS_SECRET_NAME: ${{ secrets[matrix.env.aws_secret] }}
        run: |
          echo ${ENV}
          echo ${AWS_KEY_NAME}
          echo ${AWS_SECRET_NAME}
